CREATE TABLE `ALUNOS` (
  `id_nu_insc` varchar(45) NOT NULL,
  `nu_ano` int(4) DEFAULT NULL,
  `cod_mun_res` int(7) DEFAULT NULL,
  `nome_mun_res` varchar(150) DEFAULT NULL,
  `cod_uf_res` varchar(45) DEFAULT NULL,
  `uf_res` varchar(2) DEFAULT NULL,
  `in_estuda_cl_hosp` int(1) DEFAULT NULL,
  `idade` int(100) DEFAULT NULL,
  `id_sexo` varchar(2) DEFAULT NULL,
  `id_nacionalidade` int(4) DEFAULT NULL,
  `cod_mun_nasc` int(7) DEFAULT NULL,
  `cod_us_nasc` varchar(45) DEFAULT NULL,
  `uf_nasc` varchar(2) DEFAULT NULL,
  `id_st_conclusao` int(4) DEFAULT NULL,
  `ano_conclusao` int(11) DEFAULT NULL,
  `id_tp_esc` int(2) DEFAULT NULL,
  `id_in_tp_ensino` int(4) DEFAULT NULL,
  `id_tp_estado_civil` int(4) DEFAULT NULL,
  `id_tp_cor_raca` int(6) DEFAULT NULL,
  `in_baixa_visao` int(11) DEFAULT NULL,
  `in_cegueira` int(11) DEFAULT NULL,
  `in_surdez` int(11) DEFAULT NULL,
  `in_def_auditiva` int(11) DEFAULT NULL,
  `in_surdo_cegueira` int(11) DEFAULT NULL,
  `in_def_mental` int(11) DEFAULT NULL,
  `in_def_fisica` int(11) DEFAULT NULL,
  `in_deficit_atencao` int(11) DEFAULT NULL,
  `in_dislexia` int(11) DEFAULT NULL,
  `in_lactante` int(11) DEFAULT NULL,
  `in_gestante` int(11) DEFAULT NULL,
  `in_idoso` int(11) DEFAULT NULL,
  `in_autismo` int(11) DEFAULT NULL,
  `in_sabatista` int(11) DEFAULT NULL,
  `in_braile` int(11) DEFAULT NULL,
  `in_ampliada_24` int(11) DEFAULT NULL,
  `in_ampliada_18` int(11) DEFAULT NULL,
  `in_ledor` int(11) DEFAULT NULL,
  `in_acesso` int(11) DEFAULT NULL,
  `in_transcricao` int(11) DEFAULT NULL,
  `in_libras` int(11) DEFAULT NULL,
  `in_leitura_labial` int(11) DEFAULT NULL,
  `in_mesa_cadeira_rodas` int(11) DEFAULT NULL,
  `in_mesa_cadeira_separada` int(11) DEFAULT NULL,
  `in_apoio_perna` int(11) DEFAULT NULL,
  `in_guia_interprete` int(11) DEFAULT NULL,
  `id_cod_esc` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_nu_insc`),
  KEY `id_cod_esc_idx` (`id_cod_esc`),
  KEY `id_sexo_idx` (`id_sexo`),
  KEY `id_tp_esc_idx` (`id_tp_esc`),
  KEY `id_in_tp_ensino_idx` (`id_in_tp_ensino`),
  KEY `id_tp_estado_civil_idx` (`id_tp_estado_civil`),
  KEY `id_tp_cor_raca_idx` (`id_tp_cor_raca`),
  KEY `id_nacionalidade_idx` (`id_nacionalidade`),
  KEY `id_st_conclusao_idx` (`ano_conclusao`),
  KEY `id_st_conclusao_idx1` (`id_st_conclusao`),
  CONSTRAINT `id_cod_esc` FOREIGN KEY (`id_cod_esc`) REFERENCES `ESCOLAS` (`id_cod_esc`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_in_tp_ensino` FOREIGN KEY (`id_in_tp_ensino`) REFERENCES `IN_TP_ENSINO` (`id_in_tp_ensino`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_nacionalidade` FOREIGN KEY (`id_nacionalidade`) REFERENCES `NACIONALIDADE` (`id_nacionalidade`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_sexo` FOREIGN KEY (`id_sexo`) REFERENCES `SEXO` (`id_sexo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_st_conclusao` FOREIGN KEY (`id_st_conclusao`) REFERENCES `ENSINO_MEDIO_CONCLUSAO` (`id_st_conclusao`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_tp_cor_raca` FOREIGN KEY (`id_tp_cor_raca`) REFERENCES `TP_COR_RACA` (`id_tp_cor_raca`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_tp_esc` FOREIGN KEY (`id_tp_esc`) REFERENCES `TP_ESCOLA` (`id_tp_escola`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `id_tp_estado_civil` FOREIGN KEY (`id_tp_estado_civil`) REFERENCES `TP_ESTADO_CIVIL` (`id_tp_estado_civil`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
