CREATE TABLE `PROVA` (
  `id_nu_insc` varchar(45) NOT NULL,
  `cod_mun_prova` int(11) DEFAULT NULL,
  `nome_mun_prova` varchar(45) DEFAULT NULL,
  `cod_uf_prova` varchar(45) DEFAULT NULL,
  `uf_prova` varchar(45) DEFAULT NULL,
  `in_presenca_cn` int(11) DEFAULT NULL,
  `in_presenca_ch` int(11) DEFAULT NULL,
  `in_presenca_lc` int(11) DEFAULT NULL,
  `in_presenca_mt` int(11) DEFAULT NULL,
  `id_prova_cn` int(11) DEFAULT NULL,
  `id_prova_ch` int(11) DEFAULT NULL,
  `id_prova_lc` int(11) DEFAULT NULL,
  `id_prova_mt` int(11) DEFAULT NULL,
  `nota_cn` double DEFAULT NULL,
  `nota_ch` double DEFAULT NULL,
  `nota_lc` double DEFAULT NULL,
  `nota_mt` double DEFAULT NULL,
  `tx_respostas_cn` varchar(200) DEFAULT NULL,
  `tx_respostas_ch` varchar(200) DEFAULT NULL,
  `tx_respostas_lc` varchar(200) DEFAULT NULL,
  `tx_respostas_mt` varchar(200) DEFAULT NULL,
  `tp_lingua` int(11) DEFAULT NULL,
  `id_prova` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_prova`),
  KEY `id_nu_insc_idx` (`id_nu_insc`),
  CONSTRAINT `nu_insc` FOREIGN KEY (`id_nu_insc`) REFERENCES `ALUNOS` (`id_nu_insc`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=108340 DEFAULT CHARSET=latin1;
